export enum SyntaxTreeKind{
  PROGRAM,
  FUNCTION_DEFINITION,
  FUNCTION_PARAMETERS_DEFINITION,
  BLOCK,
  RETURN,
  VARIABLE_DEFINITION,
  VARIABLE,
  BINARY_OPERATOR,
  UNARY_OPERATOR,
  FUNCTION_CALL,
  LITERAL,
}
